version: '2.1'
services:
  h2o:
    build: ./lierc-h2o
    volumes:
      - ./lierc-basicui:/opt/lierc-basicui/:ro
    ports:
      - "80:80"
      - "443:443"
    links:
      - lierc-api
      - lierc-api-stream

  basicui:
    build: ./lierc-basicui
    volumes:
      - ./lierc-basicui:/opt/lierc-basicui/:rw

  liercd:
    build: ./lierc
    command: [ liercd ]
    env_file: .env
    environment:
      LIERC_DEBUG: 2
    ports:
      - "5005:5005"
    links:
      - nsqd
    depends_on:
      nsqd:
        condition: service_started

  lierc-logger:
    build: ./lierc
    command: [ lierc-logger ]
    env_file: .env
    links:
      - postgres:database
      - nsqd
    depends_on:
      nsqd:
        condition: service_started
      postgres:
        condition:  service_healthy

  lierc-identd:
    build: ./lierc
    command: [ lierc-identd ]
    env_file: .env
    links:
      - liercd
    ports:
      - "113:113"

  lierc-notify:
    build: ./lierc
    command: [ lierc-notify ]
    env_file: .env
    links:
      - postgres
      - lierc-api
    depends_on:
      postgres:
        condition:  service_healthy

  lierc-api:
    build: ./lierc-api
    env_file: .env
    ports:
      - "5004:5004"
    links:
      - postgres:database
      - liercd
    depends_on:
      postgres:
        condition:  service_healthy


  lierc-api-stream:
    build: ./lierc-api
    command: [carton, exec, plackup, --server, Twiggy, -Ilib, --listen, ":5003", bin/stream.psgi]
    ports:
      - "5003:5003"
    env_file: .env
    links:
      - postgres:database
      - liercd
      - nsqd
    depends_on:
      nsqd:
        condition: service_started
      postgres:
        condition:  service_healthy

  postgres:
    env_file: .env
    ports:
      - "5432:5432"
    build: ./lierc-postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-U", "lierc", "-d", "lierc"]
      interval: 30s
      timeout: 30s
      retries: 3

  nsqlookupd:
    image: nsqio/nsq
    ports:
      - "4160:4160"
      - "4161:4161"
    command: /nsqlookupd

  nsqd:
    image: nsqio/nsq
    ports:
      - "4150"
      - "4151"
    links:
      - nsqlookupd:nsqlookupd
    command: /nsqd --lookupd-tcp-address=nsqlookupd:4160

  nsqadmin:
    image: nsqio/nsq
    ports:
      - "4171:4171"
    links:
      - nsqlookupd:nsqlookupd
    command: /nsqadmin --lookupd-http-address=nsqlookupd:4161
